// src/form-utils.js (ES module, 테스트가 쓰는 단일 소스) + src/app.js 를
// file:// 에서도 로드되는 '비-module' 번들 src/app.bundle.js 로 합친다.
//
// 이유: <script type="module"> 은 file:// 에서 CORS 정책으로 차단된다
// (Cross origin requests are only supported for http/https...). 일반 <script>
// 는 file:// 에서도 로드되므로, import/export 를 제거하고 하나의 IIFE 로 묶는다.
//
// 단일 소스 유지: 로직은 src/form-utils.js / src/app.js 에만 존재하고,
// 테스트(tests/form-utils.test.mjs)는 계속 src/form-utils.js 를 import 한다.
// 소스를 고치면 npm run build 로 번들을 재생성한다.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const srcDir = fileURLToPath(new URL('./src/', import.meta.url));

// export 키워드 제거 (항상 줄 맨 앞): export const / export function -> const / function
const utils = (await readFile(srcDir + 'form-utils.js', 'utf8')).replace(/^export\s+/gm, '');

// app.js 상단의 form-utils import 블록 제거
const app = (await readFile(srcDir + 'app.js', 'utf8')).replace(
  /^import\s*\{[\s\S]*?\}\s*from\s*['"]\.\/form-utils\.js['"];?\s*$/m,
  '',
);

const banner =
  '// AUTO-GENERATED by build.mjs — DO NOT EDIT.\n' +
  '// Edit src/form-utils.js / src/app.js, then run: npm run build\n';

const bundle = `${banner}(function () {\n'use strict';\n${utils}\n${app}\n})();\n`;

await writeFile(srcDir + 'app.bundle.js', bundle);
console.log(`built src/app.bundle.js (${bundle.length} bytes)`);
