// Inlines src/*.js (ES modules) into a single non-module IIFE bundle
// (src/app.bundle.js) that loads under file:// without CORS.
// Edit the source modules and run `npm run build` to regenerate.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const srcDir = fileURLToPath(new URL('./src/', import.meta.url));
const MODULES = ['form-utils.js', 'interview-client.js', 'interview-ui.js', 'app.js'];

function strip(code) {
  return code
    .replace(/^export\s+/gm, '')
    .replace(/^import\s+[\s\S]*?from\s+['"][^'"]+['"];?\s*$/gm, '');
}

const banner =
  '// AUTO-GENERATED by build.mjs — DO NOT EDIT.\n' +
  '// Edit src/*.js then run: npm run build\n';

const parts = [];
for (const name of MODULES) {
  parts.push(strip(await readFile(srcDir + name, 'utf8')));
}
const bundle = `${banner}(function () {\n'use strict';\n${parts.join('\n')}\n})();\n`;
await writeFile(srcDir + 'app.bundle.js', bundle);
console.log(`built src/app.bundle.js (${bundle.length} bytes)`);
